apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whisker-ingress
  namespace: calico-system
  labels:
    app.kubernetes.io/author: thomas-rausch
    app.kubernetes.io/instance: home-network
    app.kubernetes.io/version: 2025-12-12
    app.kubernetes.io/component: networkpolicy
    app.kubernetes.io/part-of: Calico
    app.kubernetes.io/managed-by: kubectl_apply   
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          projectcalico.org/name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: ingress-nginx
    ports:
    - port: 8081
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: whisker
  policyTypes:
  - Ingress
