# Purpose     : Form Kubernetes Object
# Object Kind : NetworkPolicy
# Object Name : deny-ingress-all_pods-ns_mysql
# Description : Deny all Ingress network traffic in the namespace "mysql"
# Author      : Tom Rausch, Atos
#
# Kubernetes API Resource
# -----------------------
# NAME             SHORTNAMES  APIVERSION            NAMESPACED   KIND
# networkpolicies  netpol      networking.k8s.io/v1  true         NetworkPolicy
#
apiVersion: networking.k8s.io/v1            # Set API resource
kind: NetworkPolicy                         # Set object kind
metadata:
  name: deny-ingress-all_pods-ns_mysql      # Set object name
  namespace: mysql                          # Object is in effect in Namespace "mysql"     
spec:
  podSelector: {}                           # Select all Pods in the Namespace
  policyTypes:
  - Ingress                                 # Set Policy Type = "Ingress"
