apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  generation: 1
  name: deny-ingress-all_pods-ns_mysql
  namespace: mysql  # Form in namespace "mysql"
spec:
  podSelector: {}   # Select all pods in the namespace
  policyTypes:
  - Ingress         # Set Policy Type = "Ingress"
